Repository 2024-TikiTaka/fe-triptroop, pull requests merged in 2024-06, with the labels that each got.

#10 #4 채팅창 구현
  package-lock.json
  package.json
  src/components/chat/ChatBox.css
  src/components/chat/ChatBox.js
  src/components/chat/ChatList.js
  src/components/chat/ChatRoom.js
  src/components/chat/FriendList.js
  src/components/chat/NoticeList.js
  src/components/common/Header.js
Labels: ✨ Feature

#13 README.md 수정
  README.md
Labels: 📚 Docs

#16 로그인, 로그아웃 구현 및 공통 레이아웃 수정
  public/index.html
  public/manifest.json
  src/App.js
  src/apis/UserAPICalls.js
  src/apis/api.js
  src/common.css
  src/components/box/ChatBox.js
  src/components/box/ProfileBox.js
  src/components/common/Footer.js
  src/components/common/Header.js
  src/components/common/Wrapper.js
  src/components/custom/CustomInput.js
  src/components/form/LoginForm.js
  src/components/form/SignupForm.js
  src/components/item/ChatRoom.js
  src/components/list/ChatList.js
  src/components/list/FriendList.js
  src/components/list/NoticeList.js
  src/components/router/ProtectedRoute.js
  src/index.js
  src/layouts/Layout.js
  src/modules/UserModules.js
  src/modules/index.js
  src/pages/error/Error.js
  src/pages/user/Login.js
  src/pages/user/Signup.js
  src/store.js
  src/styles/chat.css
  src/styles/common.css
  src/utils/TokenUtils.js
Labels: ✨ Feature, 🎨Layout

#21 권한 별 레이아웃 분리 및 로그아웃 수정
  src/App.js
  src/apis/UserAPICalls.js
  src/apis/api.js
  src/components/common/Header.js
  src/components/common/PagingBar.js
  src/components/custom/CustomInput.js
  src/components/pagination/PagingBar.js
  src/components/router/ProtectedRoute.js
  src/layouts/AdminLayout.js
  src/pages/admin/AdminMain.js
  src/pages/main/Main.js
Labels: ✨ Feature, 🎨Layout

#22 #14 일정 목록 조회 페이징
  src/App.js
  src/apis/ScheduleAPICalls.js
  src/components/item/Schedules.js
  src/components/list/ScheduleList.js
  src/components/pagination/PagingBar.js
  src/modules/ScheduleModules.js
  src/modules/index.js
  src/pages/schedule/SchedulesList.js
  src/pages/schedule/SearchScheduleList.js
Labels: ✨ Feature

#24 #23 일정 상세 조회
  src/App.js
  src/apis/ScheduleAPICalls.js
  src/components/item/ScheduleItem.js
  src/components/item/ScheduleListItem.js
  src/components/list/ScheduleList.js
  src/modules/ScheduleModules.js
  src/pages/schedule/ScheduleDetail.js
  src/pages/schedule/SchedulesList.js
  src/pages/schedule/SearchScheduleList.js
Labels: ✨ Feature

#25 #18 회원 가입 구현, react-hook-form 라이브러리 추가
  package-lock.json
  package.json
  src/apis/UserAPICalls.js
  src/apis/api.js
  src/components/common/Footer.js
  src/components/common/Header.js
  src/components/common/Icons.js
  src/components/custom/CustomDivider.js
  src/components/custom/CustomInput.js
  src/components/form/LoginForm.js
  src/components/form/SignupForm.js
  src/modules/UserModules.js
  src/pages/user/Login.js
  src/pages/user/Signup.js
  src/styles/common.css
  src/styles/user.css
Labels: ✨ Feature, 🎨Layout

#28 #27 모달 컴포넌트 추가
  src/components/common/ModalPopup.js
  src/components/custom/CustomModal.js
  src/styles/chat.css
Labels: ✨ Feature, 🎨Layout

#29 #26 일정 등록
  package-lock.json
  package.json
  src/App.js
  src/apis/ScheduleAPICalls.js
  src/components/form/ScheduleForm.js
  src/components/item/ScheduleItem.js
  src/pages/schedule/ScheduleRegist.js
Labels: ✨ Feature

#32 #31 ProtectedRoute 및 로그인 처리, 기타 레이아웃 수정
  src/App.js
  src/apis/AuthAPICalls.js
  src/apis/ScheduleAPICalls.js
  src/apis/UserAPICalls.js
  src/components/button/KakaoButton.js
  src/components/button/NaverButton.js
  src/components/common/Header.js
  src/components/common/Icons.js
  src/components/custom/CustomDivider.js
  src/components/form/LoginForm.js
  src/components/form/ProfileInfoForm.js
  src/components/form/UserInfoForm.js
  src/components/router/ProtectedRoute.js
  src/index.js
  src/layouts/Layout.js
  src/modules/UserModules.js
  src/pages/user/KakaoAuth.js
  src/pages/user/Login.js
  src/pages/user/Signup.js
  src/pages/user/UserInfo.js
Labels: 🔧Refactor, 🎨Layout

#35 #19, #34 회원 정보 조회 및 마이페이지, 설정 페이지 레이아웃
  src/App.js
  src/apis/UserAPICalls.js
  src/components/box/ProfileBox.js
  src/components/common/Header.js
  src/components/common/SettingsNavbar.js
  src/components/content/MyPageContent.js
  src/components/content/SettingsContent.js
  src/components/form/ProfileForm.js
  src/components/form/ProfileInfoForm.js
  src/components/form/UserInfoForm.js
  src/components/item/ChatBox.js
  src/modules/UserModules.js
  src/modules/index.js
  src/pages/mypage/MyPage.js
  src/pages/settings/UserSettings.js
  src/pages/user/UserInfo.js
  src/styles/user.css
Labels: ✨ Feature, 🎨Layout

#36 #30 일정 계획 카카오 맵 등록
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/apis/ScheduleAPICalls.js
  src/components/form/ScheduleForm.js
  src/components/form/ScheduleItemForm.js
  src/components/item/ScheduleItem.js
  src/components/map/KaKaoMapAPI.js
  src/pages/schedule/ScheduleRegist.js
Labels: ✨ Feature

#38 #15 여행지 소개 전체조회 및 상세 조회
  .env
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/apis/TravelCalls..js
  src/apis/api.js
  src/components/item/PlaceItem.js
  src/components/item/TravelCommentListItem.js
  src/components/item/TravelItem.js
  src/components/item/TravelListItem.js
  src/components/list/TravelCommentList.js
  src/components/list/TravelList.js
  src/modules/PlaceModules.js
  src/modules/TravelCommentModules.js
  src/modules/TravelModules.js
  src/modules/index.js
  src/pages/travel/KakaoMap.js
  src/pages/travel/TravelDetail.js
  src/pages/travel/TravelMain.js
  src/pages/travel/TravelNavber.js
  src/pages/travel/kakaoMapTest.js
  src/styles/JobPostingsStatus.css
Labels: ✨ Feature

#42 #33 관리자 페이지 레이아웃 셋팅
  public/images/admin_logo.svg
  public/images/icon_admin_ notice.png
  public/images/icon_admin_category.png
  public/images/icon_admin_inquiry.png
  public/images/icon_admin_user.png
  public/index.html
  src/App.js
  src/apis/AdminAPICalls.js
  src/apis/UserAPICalls.js
  src/components/common/Header.js
  src/components/common/SettingsNavbar.js
  src/components/common/admin/AdminHeader.js
  src/components/common/admin/AdminNav.js
  src/components/content/MyPageContent.js
  src/components/content/SettingsContent.js
  src/components/form/ProfileForm.js
  src/components/form/ProfileInfoForm.js
  src/components/form/UserInfoForm.js
  src/components/item/ChatBox.js
  src/components/item/admin/AdminUserDetail.js
  src/components/item/admin/AdminUserItem.js
  src/components/list/AdminUserList.js
  src/components/router/ProtectedRoute.js
  src/layouts/AdminLayout.js
  src/modules/AdminModules.js
  src/modules/ScheduleModules.js
  src/modules/UserModules.js
  src/modules/index.js
  src/pages/admin/AdminMain.js
  src/pages/admin/category/AdminCategories.js
  src/pages/admin/category/AdminCategoryModify.js
  src/pages/admin/category/AdminCategoryRegist.js
  src/pages/admin/inquiry/AdminInquiries.js
  src/pages/admin/inquiry/AdminInquiryDetail.js
  src/pages/admin/inquiry/AdminInquiryRegist.js
  src/pages/admin/user/AdminUserDelete.js
  src/pages/admin/user/AdminUserDetail.js
  src/pages/admin/user/AdminUserRegist.js
  src/pages/admin/user/AdminUsers.js
  src/pages/mypage/MyPage.js
  src/pages/settings/UserSettings.js
  src/pages/user/Login.js
  src/styles/admin.css
  src/styles/user.css
  src/utils/TokenUtils.js
Labels: ⚙️Setting, 🔧Refactor, 🎨Layout

#46 #37 일정 상세 조회 시 카카오맵 불러오기
  src/components/item/ScheduleItem.js
  src/components/map/kakaoMapSelect.js
  src/pages/schedule/ScheduleDetail.js
Labels: ✨ Feature

#45 #39 여행지 등록
  public/index.html
  src/App.js
  src/apis/TravelAPICalls.js
  src/components/form/TravelForm.js
  src/modules/TravelModules.js
  src/pages/travel/TravelDetail.js
  src/pages/travel/TravelMain.js
  src/pages/travel/TravelRegist.js
Labels: ✨ Feature

#53 #43 관리자 > 회원 관리 > 회원 목록 조회
  public/images/admin_logo.svg
  public/images/icon_admin_ notice.png
  public/images/icon_admin_category.png
  public/images/icon_admin_inquiry.png
  public/images/icon_admin_user.png
  src/App.js
  src/apis/AdminAPICalls.js
  src/apis/admin/AdminUserAPICalls.js
  src/components/box/ChatBox.js
  src/components/box/ProfileBox.js
  src/components/item/CustomTable.js
  src/components/item/admin/AdminUserDetail.js
  src/components/list/AdminUserList.js
  src/components/list/admin/AdminUserList.js
  src/layouts/AdminLayout.js
  src/modules/admin/AdminUserModules.js
  src/modules/index.js
  src/pages/admin/main/AdminMain.js
  src/pages/admin/user/AdminUserDetail.js
  src/pages/admin/user/AdminUserRegist.js
  src/pages/admin/user/AdminUsers.js
  src/pages/user/UserInfo.js
  src/styles/admin.css
Labels: ✨ Feature

#54 여행지 소개 삭제
  src/apis/TravelAPICalls.js
  src/pages/travel/TravelDetail.js
Labels: ✨ Feature

#56 #44 관리자 > 회원 관리 > 회원 상세 조회
  src/App.js
  src/apis/admin/AdminCategoryAPICalls.js
  src/apis/admin/AdminInquiryAPICalls.js
  src/apis/admin/AdminNoticeAPICalls.js
  src/apis/admin/AdminUserAPICalls.js
  src/components/custom/dl/DescriptionList.js
  src/components/custom/dl/TranslateKeys.js
  src/components/custom/dl/Translates.js
  src/components/custom/table/CustomTable.js
  src/components/item/TravelItem.js
  src/components/list/admin/AdminUserList.js
  src/modules/admin/AdminCategoryModules.js
  src/modules/admin/AdminInquiryModules.js
  src/modules/admin/AdminModules.js
  src/modules/admin/AdminNoticeModules.js
  src/pages/admin/AdminMain.js
  src/pages/admin/inquiry/AdminInquiryRegist.js
  src/pages/admin/inquiry/AdminInquiryRegister.js
  src/pages/admin/user/AdminUserDetail.js
  src/styles/admin.css
Labels: ✨ Feature, ⚙️Setting, 🔧Refactor

#61 #60 레이아웃 수정 및 카카오맵 키 환경 변수로 분리
  public/index.html
  src/App.js
  src/apis/AuthAPICalls.js
  src/apis/ProfileAPICalls.js
  src/apis/UserAPICalls.js
  src/components/box/ChatBox.js
  src/components/box/ProfileBox.js
  src/components/button/KakaoButton.js
  src/components/common/Header.js
  src/components/common/MyPageHeader.js
  src/components/common/ProfileImage.js
  src/components/common/SettingNavbar.js
  src/components/common/admin/AdminHeader.js
  src/components/content/MyPageContent.js
  src/components/content/SettingContent.js
  src/components/form/LoginForm.js
  src/components/form/PasswordForm.js
  src/components/form/ProfileForm.js
  src/components/form/ProfileInfoForm.js
  src/components/form/SignupForm.js
  src/components/form/UserInfoForm.js
  src/components/form/WithdrawalForm.js
  src/components/map/KaKaoMapAPI.js
  src/components/map/kakaoMapSelect.js
  src/layouts/Layout.js
  src/layouts/MyPageLayout.js
  src/modules/ProfileModules.js
  src/modules/index.js
  src/pages/mypage/MyHome.js
  src/pages/mypage/MyLikes.js
  src/pages/mypage/MyPageMain.js
  src/pages/mypage/MySchedules.js
  src/pages/mypage/MyTravels.js
  src/pages/settings/MyProfile.js
  src/pages/settings/MyUserInfo.js
  src/pages/settings/PasswordSettings.js
  src/pages/settings/ProfileSettings.js
  src/pages/settings/ReportSettings.js
  src/pages/settings/UserSettings.js
  src/pages/settings/Withdrawal.js
  src/pages/travel/KakaoMap.js
  src/pages/travel/kakaoMapTest.js
  src/styles/sub.css
Labels: ⚙️Setting, 🎨Layout

#62 #50 일정 수정,삭제,신청,승인,반려,일정 참여자 조회
  public/index.html
  src/App.js
  src/apis/ScheduleAPICalls.js
  src/components/form/ScheduleForm.js
  src/components/form/ScheduleItemForm.js
  src/components/form/ScheduleItemUpdateForm.js
  src/components/form/ScheduleUpdateForm.js
  src/components/item/ScheduleItem.js
  src/components/item/ScheduleListItem.js
  src/components/item/ScheduleParticipantsListItem.js
  src/components/list/ScheduleParticipantsList.js
  src/components/list/SchedulesList.js
  src/modules/ScheduleParticipantModules.js
  src/modules/index.js
  src/pages/schedule/Schedule.js
  src/pages/schedule/ScheduleAccept.js
  src/pages/schedule/ScheduleApply.js
  src/pages/schedule/ScheduleDetail.js
  src/pages/schedule/ScheduleItemRemove.js
  src/pages/schedule/ScheduleItemUpdate.js
  src/pages/schedule/ScheduleParticipant.js
  src/pages/schedule/ScheduleRejected.js
  src/pages/schedule/ScheduleRemove.js
  src/pages/schedule/ScheduleUpdate.js
Labels: ✨ Feature

#65 #64 여행지 소개 부트스트랩 적용
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/apis/TravelAPICalls.js
  src/components/custom/VisualSlider.js
  src/components/form/TravelForm.js
  src/components/item/TravelCommentListItem.js
  src/components/item/TravelItem.js
  src/components/item/TravelListItem.js
  src/components/list/TravelList.js
  src/components/map/KaKaoMapAPI.js
  src/components/map/kakaoMapSelect.js
  src/modules/TravelCommentModules.js
  src/pages/travel/KakaoMap.js
  src/pages/travel/TravelDetail.js
  src/pages/travel/TravelMain.js
  src/pages/travel/kakaoMapTest.js
  src/styles/TravelListmodule.css
  src/styles/travel.css
Labels: 🎨Layout

#66 #11 채팅방 생성
  .env
  package-lock.json
  package.json
  src/components/form/ProfileInfoForm.js
  src/components/item/ChatBox.js
  src/components/item/ChatRoom.js
  src/components/item/CustomTable.js
  src/components/list/ChatList.js
  src/components/list/FriendList.js
  src/components/list/NoticeList.js
  src/pages/admin/AdminMain.js
  src/pages/admin/inquiry/AdminInquiryRegist.js
  src/pages/main/Main.js
  src/pages/mypage/MyPageMain.js
  src/pages/settings/ChangePassword.js
  src/pages/settings/MyProfile.js
  src/pages/settings/MyUserInfo.js
  src/styles/chat.css
  src/utils/TokenUtils.js
Labels: ✨ Feature

#68 공지 목록 조회, 상세 조회
  src/components/item/ChatBox.js
  src/components/item/NoticeItem.js
  src/components/list/NoticeList.js
  src/styles/chat.css
Labels: ✨ Feature

#70 #69 검색 기능 수정
  src/apis/ScheduleAPICalls.js
  src/components/form/ScheduleUpdateForm.js
  src/components/item/ScheduleItem.js
  src/components/item/ScheduleListItem.js
  src/components/list/SchedulesList.js
  src/pages/schedule/Schedule.js
  src/pages/schedule/ScheduleDetail.js
Labels: 🔧Refactor

#71 #20 마이페이지, 설정 관련 기능 및 레이아웃
  .env
  .gitignore
  public/images/default_profile.svg
  src/App.js
  src/apis/AuthAPICalls.js
  src/apis/ProfileAPICalls.js
  src/apis/UserAPICalls.js
  src/components/button/EmailButton.js
  src/components/button/KakaoButton.js
  src/components/button/NaverButton.js
  src/components/common/Header.js
  src/components/common/MyPageHeader.js
  src/components/common/ProfileImage.js
  src/components/common/SettingNavbar.js
  src/components/content/MyPageContent.js
  src/components/content/SettingContent.js
  src/components/form/FindPasswordForm.js
  src/components/form/LoginForm.js
  src/components/form/PasswordForm.js
  src/components/form/ProfileForm.js
  src/components/form/SignupForm.js
  src/components/form/UserInfoForm.js
  src/components/list/TravelList.js
  src/components/modal/ModalPopup.js
  src/components/router/ProtectedRoute.js
  src/modules/ProfileModules.js
  src/modules/UserModules.js
  src/modules/index.js
  src/pages/main/Main.js
  src/pages/mypage/MyPageMain.js
  src/pages/settings/MyProfile.js
  src/pages/settings/MyUserInfo.js
  src/pages/settings/ProfileSettings.js
  src/pages/settings/UserSettings.js
  src/pages/settings/Withdrawal.js
  src/pages/user/FindPassword.js
  src/pages/user/Login.js
  src/pages/user/Signup.js
  src/pages/user/UserInfo.js
  src/styles/JobPostingsStatus.css
  src/styles/TravelListmodule.css
Labels: ✨ Feature, 🎨Layout

#72 env 관련 설정 수정
  public/index.html
  src/apis/api.js
  src/components/map/KaKaoMapAPI.js
  src/components/map/kakaoMapSelect.js
  src/pages/travel/KakaoMap.js
  src/pages/travel/kakaoMapTest.js
Labels: ⚙️Setting

#78 여행지 소개 레이아웃 적용
  src/components/custom/VisualSlider.js
  src/components/form/TravelModifyForm.js
  src/components/item/TravelCommentListItem.js
  src/components/item/TravelListItem.js
  src/components/list/TravelList.js
  src/pages/travel/TravelMain.js
Labels: 🎨Layout
